# Generated by Django 6.0.5 on 2026-05-14 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profesor.profesor')),
            ],
        ),
    ]
