# Generated by Django 6.0.5 on 2026-05-14 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignatura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('EXAMEN', 'Examen'), ('TRABAJO', 'Trabajo'), ('PRACTICA', 'Practica')], max_length=20)),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignatura.asignatura')),
            ],
        ),
    ]
